export const windowOptions = [
  {
    id: 1,
    name: "Experiencias",
    isFile: true,
    url_image: "/file.png",
    isOpen: false,
    isDisplay: false,
    experiences: [
      {
        id: 1,
        name: "Desarrollador Fullstack/Soporte",
        company_name: "Intercar Chile SPA",
        start_date: "07/2023",
        finish_date: "03/2026",
        description: `Evalue e integre nuevas tecnologías, como a su vez se realizo la capacitación de estás.\n
           Se entrego soporte informático a más de 12 usuarios.\n
           Desarrollo de plataformas internas con tecnologías actuales (fullstack)\n
           Documentación y diseño de dichos desarrollos.\n
           Monitoreo y mantención del cpanel de la empresa y sus correos.\n
           Se entregaron informes SQL y realizaron migraciones a diferentes servidores\n`,
        isCurrent: true,
        tecnologies: [
          { id: 1, name: "Node.js" },
          { id: 2, name: "Express.js" },
          { id: 3, name: "Jest" },
          { id: 4, name: "Sequelize" },
          { id: 5, name: "Astro.Js" },
          { id: 6, name: "React.Js" },
          { id: 7, name: "Tailwind" },
          { id: 8, name: "Php" },
          { id: 9, name: "Sql" },
          { id: 10, name: "Docker" },
          { id: 11, name: "Mysql" },
          { id: 12, name: "Powerbi" },
          { id: 12, name: "JWT/Auth" },
          { id: 12, name: "Diseño base de datos" },
        ],
      },
      {
        id: 2,
        name: "Supervisor de ventas",
        company_name: "Intercar chile SPA",
        start_date: "07/2023",
        finish_date: "12/2025",
        description:
          "Supervisión de equipo de ventas, manejo de clientes y coordinación con otros departamentos. Además de analisis de venta, rotación de productos y apoyo al área logistica a tráves de informes SQL y PowerBI.",
        isCurrent: true,
        tecnologies: [
          { id: 9, name: "SQL" },
          { id: 10, name: "Excel avanzado" },
          { id: 11, name: "PowerBI" },
        ],
      },
      {
        id: 3,
        name: "Coodinador TI",
        company_name: "Intercar chile SPA",
        start_date: "07/2020",
        finish_date: "08/2021",
        description:
          "Coordinación de proyectos TI con trabajadores externos. Además de migración de ERP Kreasoft (respaldos SQL) a ERP Defontana, capacitando e implementando el nuevo ERP a los trabajadores de la empresa ",
        isCurrent: true,
        tecnologies: [
          { id: 9, name: "SQL" },
          { id: 10, name: "Excel avanzado" },
          { id: 11, name: "PowerBI" },
        ],
      },
      {
        id: 4,
        name: "Analista contable",
        company_name: "Intercar chile SPA",
        start_date: "07/2018",
        finish_date: "06/2020",
        description:
          "Auditoria de los cierres de sucursales, además de el seguimiento de DTE electronico a plataforma GDEXPRESS. Teniendo en cuenta su llegada correcta al SII. Reportes diarios y mensuales de ventas, entre otros.",
        isCurrent: true,
        tecnologies: [{ id: 10, name: "Excel avanzado" }],
      },
      {
        id: 5,
        name: "Jefe sucursal",
        company_name: "Intercar chile SPA",
        start_date: "06/2018",
        finish_date: "01/2017",
        description:
          "Liderazgo del equipo de trabajo (3 personas), creando un ambiente ameno para el grupo de trabajo. Además de mantener los productos disponibles teniendo en cuenta los quiebres de stock de la sucursal. Cabe mencionar que se logro el hito de alcanzar la meta durante 6 meses consecutivos.",
        isCurrent: true,
        tecnologies: [],
      },
      {
        id: 6,
        name: "Vendedor",
        company_name: "Intercar chile SPA",
        start_date: "06/2016",
        finish_date: "01/2017",
        description:
          "Atención al cliente, ofreciendo el producto adecuado. Área automotriz",
        isCurrent: true,
        tecnologies: [],
      },
      ,
    ],
  },
  {
    id: 2,
    name: "Tecnologías",
    isFile: true,
    url_image: "/file.png",
    isOpen: false,
    isDisplay: false,
    experiences: [
      {
        id: 1,
        description:
          "Tecnologías que he utilizado o he estudiado en el ámbito del desarrollo de software. Esto incluye tecnologías backend como bases de datos.",
        isCurrent: true,
        name: "Backend",
        tecnologies: [
          { id: 1, name: "Node.js" },
          { id: 2, name: "Express.js" },
          { id: 3, name: "Nestjs.js" },
          { id: 4, name: "Golang" },
          { id: 5, name: "Echo go" },
          { id: 6, name: "Sequelize.js" },
          { id: 7, name: "Typeorm" },
          { id: 8, name: "JWT/Auth" },
          { id: 9, name: "Php" },
          { id: 10, name: "PLSQL" },
          { id: 11, name: "Diseño base de datos" },
        ],
      },
      {
        id: 2,
        description:
          " Tecnologías que he utilizado o he estudiado en el ámbito del desarrollo de software. Esto incluye tecnologías frontend como frameworks, librerías y herramientas relacionadas.",
        isCurrent: true,
        name: "Frontend",
        tecnologies: [
          { id: 12, name: "Nextjs.js" },
          { id: 13, name: "React.js" },
          { id: 14, name: "Tailwindcss" },
          { id: 15, name: "Css" },
          { id: 16, name: "Javascript" },
          { id: 17, name: "React native" },
          { id: 18, name: "Astro.js" },
          { id: 19, name: "ContextAPI" },
          { id: 20, name: "React router" },
        ],
      },
      {
        id: 3,
        description:
          "Tecnologías relacionadas con la nube y arquitecturas de software.",
        isCurrent: true,
        name: "Cloud y arquitecturas",
        tecnologies: [
          { id: 21, name: "AWS" },
          { id: 22, name: "Docker" },
          { id: 23, name: "Linux" },
          { id: 24, name: "MVC arquitectura" },
          { id: 25, name: "Arquitectura por capas" },
          { id: 26, name: "Desarrollo modular" },
        ],
      },
      {
        id: 4,
        description:
          "Otras tecnologías relacionadas con el desarrollo de software.",
        isCurrent: true,
        name: "Otras",
        tecnologies: [
          { id: 27, name: "Excel avanzado" },
          { id: 28, name: "Power BI" },
          { id: 29, name: "UML" },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Proyectos",
    isFile: true,
    url_image: "/file.png",
    isOpen: false,
    isDisplay: false,
    experiences: [
      {
        id: 1,
        name: "Web Aguiplas",
        company_name: "Aguiplas S.A",
        start_date: "01/2026",
        finish_date: "01/2026",
        description:
          "Implementación de página web en Wordpress. Además de conexión de la página con los DNS del cliente y leve configuración del cpanel.",
        isCurrent: true,
        tecnologies: [
          { id: 9, name: "Php" },
          { id: 30, name: "Wordpress" },
        ],
      },
      {
        id: 2,
        name: "Full stack Intercar",
        company_name: "Intercar chile SPA",
        start_date: "01/2025",
        finish_date: "06/2025",
        description:
          "Desarrollo full stack de plataforma e-commerce con tecnologías modernas. Integrando el stock de la empresa y desplegando este para los clientes finales.",
        isCurrent: true,
        tecnologies: [
          { id: 1, name: "Node.js" },
          { id: 2, name: "Express.js" },
          { id: 6, name: "Sequelize.js" },
          { id: 8, name: "JWT/Auth" },
          { id: 10, name: "PLSQL" },
          { id: 11, name: "Diseño base de datos" },
          { id: 13, name: "React.js" },
          { id: 14, name: "Tailwindcss" },
          { id: 15, name: "Css" },
          { id: 16, name: "Javascript" },
          { id: 18, name: "Astro.js" },
          { id: 19, name: "ContextAPI" },
          { id: 20, name: "React router" },
          { id: 22, name: "Docker" },
          { id: 23, name: "Linux" },
          { id: 29, name: "UML" },
        ],
      },
      {
        id: 3,
        name: "Portafolio windows",
        start_date: "03/2026",
        finish_date: "03/2026",
        description:
          "Desarrollo full stack de mi portafolio, inspirado en windows 98. Utilizando buenas practicas, además de tecnologías a la vanguardia.",
        isCurrent: true,
        tecnologies: [
          { id: 4, name: "Golang" },
          { id: 5, name: "Echo go" },
          { id: 8, name: "JWT/Auth" },
          { id: 11, name: "Diseño base de datos" },
          { id: 13, name: "React.js" },
          { id: 12, name: "Nextjs.js" },
          { id: 14, name: "Tailwindcss" },
          { id: 15, name: "Css" },
          { id: 16, name: "Javascript" },
          { id: 22, name: "Docker" },
          { id: 23, name: "Linux" },
          { id: 29, name: "UML" },
          { id: 25, name: "Arquitectura por capas" },
          { id: 21, name: "AWS" },
        ],
      },
      {
        id: 4,
        name: "Morfeo App",
        start_date: "03/2026",
        finish_date: "04/2026",
        description:
          "Desarrollo Fullstack plataforma control de asistencia y registros de llegada. Versiones web y mobile.",
        isCurrent: true,
        tecnologies: [
          { id: 1, name: "Node.js" },
          { id: 2, name: "Express.js" },
          { id: 3, name: "Nestjs.js" },
          { id: 7, name: "Typeorm" },
          { id: 8, name: "JWT/Auth" },
          { id: 11, name: "Diseño base de datos" },
          { id: 12, name: "Nextjs.js" },
          { id: 13, name: "React.js" },
          { id: 14, name: "Tailwindcss" },
          { id: 15, name: "Css" },
          { id: 16, name: "Javascript" },
          { id: 17, name: "React native" },
          { id: 19, name: "ContextAPI" },
          { id: 21, name: "AWS" },
          { id: 22, name: "Docker" },
          { id: 23, name: "Linux" },
          { id: 24, name: "MVC arquitectura" },
          { id: 25, name: "Arquitectura por capas" },
          { id: 26, name: "Desarrollo modular" },
          { id: 29, name: "UML" },
        ],
      },
    ],
  },
  {
    id: 98,
    name: "Terminal_",
    isFile: false,
    url_image: "/cmd.png",
    isOpen: false,
    isDisplay: false,
    experiences: [],
  },
  {
    id: 99,
    name: "Ayuda",
    isFile: false,
    url_image: "/clippy.png",
    isOpen: false,
    isDisplay: false,
    experiences: [],
  },
  {
    id: 100,
    name: "Bienvenid@",
    isFile: false,
    url_image: "/clippy.png",
    isOpen: true,
    isDisplay: false,
    experiences: [],
  },
];
